[package]
name = "raytrace_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.7.3"
image = "0.24.7"
indicatif = "0.17.6"
nalgebra = "0.32.3"
rand = "0.8.5"
